version: '3'
services:
  worker:
    build:
      context: ./worker
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - humansbestfriend-network

  vote:
    build:
      context: ./vote
    volumes:
      - ./vote:/usr/local/app
    ports:
      - "5002:80"
    networks:
      - humansbestfriend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  seed-data:
    build:
      context: ./seed-data
    depends_on:
      vote:
        condition: service_healthy
    restart: "no"
    networks:
      - humansbestfriend-network

  result:
    build:
      context: ./result
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./result:/usr/local/app
    ports:
      - "5001:80"
      - "127.0.0.1:9229:9229"
    networks:
      - humansbestfriend-network

  db:
    image: postgres:15-alpine
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/postgres.sh
      interval: "5s"
    networks:
      - humansbestfriend-network

  redis:
    image: redis
    networks:
      - humansbestfriend-network
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: /healthchecks/redis.sh
      interval: "5s"

networks:
  humansbestfriend-network:
    external: true

volumes:
  db-data:
    external: false
